### PR TITLE
Stopped multiple openings

### PR DESCRIPTION
**Pull request by hiblen**
Fixed bug allowing boxes to be opened multiple times

### CODE REVIEW

**Comment by nickmeldrum** [comment]
Would love to accept a pull request from you my lovely, but have you pulled the latest before creating this pull request? :)

**Comment by hiblen** [comment]
Thanks - looks like you deleted all your tests and already added my improvement!  No idea how I ended up with the old version of the repo - I will try harder next time!

**Comment by nickmeldrum** [comment]
yeah, i decided all the tests except the ones at the highest level were not
very useful and very coupled to the implementation - outside in testing for
the win. And apologies yes but just a couple of days before your PR I did a
big refactor that indeed included the same improvement you made :) please
keep sending me PR's though :)

**Comment by nickmeldrum** [comment]
To be honest there are still quite a few valid tests that should be there
at the module level - i have a TODO: to add them back (TDD fail!)

**Pull request closed without merging**
